# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afe0753b87379480e74f63f2f24a07bcfecba773a6697ba71d3abb1161cc4923a6e3688a1480afa82a8db896fc72a45152c5da2a8d7430fc452c89ab4fcb2514

test:
  secret_key_base: 7036186e0b320ab5c7205ed2928e259add53e873f83dbae12ca5a40890ceb10141825e400fc273d33dea32a48099f857ca79fcdf4b49c5d77b6b7430006f8dcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
